lib/alewordfire_web/router.ex
defmodule AlewordfireWeb.Router do
  use AlewordfireWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Metatags
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", AlewordfireWeb do
    pipe_through :browser

    get "/about", AboutController, :index
    get "/blog/:page", PageController, :index, as: :blog_page
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", AlewordfireWeb do
  #   pipe_through :api
  # end
end

lib/alewordfire/application.ex
defmodule Alewordfire.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Cache,
      {Cachex, :network},
      # Start the endpoint when the application starts
      AlewordfireWeb.Endpoint
      # Starts a worker by calling: Alewordfire.Worker.start_link(arg)
      # {Alewordfire.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Alewordfire.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    AlewordfireWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/alewordfire/data.ex
defmodule Alewordfire.Data do
end

lib/alewordfire/data/experience.ex
defmodule Alewordfire.Data.Experience do
  @experience "priv/experience.json" |> File.read!() |> Jason.decode!()
  def data do
    @experience
  end
end

lib/alewordfire/data/feed.ex
defmodule Alewordfire.Data.Feed do
  def data do
    url = "https://medium.com/feed/@aleworld"

    xml =
      with nil <- Cachex.get!(:network, url) do
        HTTPoison.start()

        with %HTTPoison.Response{status_code: 200, body: xml} <- HTTPoison.get!(url) do
          Cachex.put(:network, url, xml, ttl: 5 * 60 * 1000)
          xml
        end
      end

    xml
    |> ElixirFeedParser.parse()
  end
end

lib/alewordfire/tools.ex
defmodule Alewordfire.Tools do
end

lib/alewordfire/tools/paginator.ex
defmodule Alewordfire.Tools.Paginator do

  def init(data, opts \\ []) when is_list(opts) do
    per = Keyword.get(opts, :per, 5)

    %{
      total_pages: Float.ceil(length(data) / per) |> Kernel.trunc(),
      per: per
    }
  end

  def calculate(data, %{"page" => page}) when is_binary(page) do
    with {current_page, _} <- Integer.parse(page) do
      calculate(data, current_page: current_page)
    end
  end
  def calculate(data, %{}), do: calculate(data, [])
  def calculate(%{total_pages: total_pages} = data, opts) when total_pages > 0 do
    current_page = Keyword.get(opts, :current_page, 1)

    data
    |> Map.merge(%{
      current_page: current_page,
      next_page: current_page + 1,
      previous_page: current_page - 1,
      has_next: current_page < total_pages,
      has_previous: current_page > 1
    })
  end
end

lib/alewordfire_web/controllers/about_controller.ex
defmodule AlewordfireWeb.AboutController do
  use AlewordfireWeb, :controller

  def index(conn, _params) do
    conn
    |> render("index.html")
  end
end

lib/alewordfire_web/controllers/page_controller.ex
defmodule AlewordfireWeb.PageController do
  use AlewordfireWeb, :controller

  def index(conn, params) do
    page = Map.get(params, "page", 1)
    canonical_path = Routes.blog_page_path(conn, :index, page)

    conn
    |> assign(:canonical_path, canonical_path)
    |> render("index.html")
  end
end

lib/alewordfire_web/views/about_view.ex
defmodule AlewordfireWeb.AboutView do
  use AlewordfireWeb, :view

  def render_section(section, opts) do
    render(
        AlewordfireWeb.AboutView,
        "section.html",
        [template: section] ++ opts
      )
  end
end

lib/alewordfire_web/views/error_view.ex
defmodule AlewordfireWeb.ErrorView do
  use AlewordfireWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/alewordfire_web/views/layout_view.ex
defmodule AlewordfireWeb.LayoutView do
  use AlewordfireWeb, :view
end

lib/alewordfire_web/views/page_view.ex
defmodule AlewordfireWeb.PageView do
  alias Alewordfire.Tools.Paginator
  use AlewordfireWeb, :view

  def create_paginator(entries) do
    Paginator.init(entries, per: 3)
  end

  def paginate(paginator, params) do
    Paginator.calculate(paginator, params)
  end

  def filter_posts(entries) do
    entries
    |> Enum.reject(fn entry ->
      comparable =
        entry.content
        |> String.split("_/stat", trim: true)
        |> List.first()

      from_title = "<p>#{entry.title}</p><img src=\"https://medium.com/"

      String.length(comparable) == String.length(from_title)
    end)
  end

  def paginate_posts(entries, %{current_page: current_page, per: per}) do
    offset = (current_page - 1) * per
    Enum.slice(entries, offset, per)
  end

  def post_date(date) do
    with {:ok, date} <- Timex.parse(date, "{RFC1123}"),
         {:ok, relative_str} <- Timex.format(date, "{relative}", :relative) do
      relative_str
    end
  end

  def post_ts(date) do
    with {:ok, date} <- Timex.parse(date, "{RFC1123}") do
      Timex.to_unix(date)
    end
  end

  def primary_image(nil), do: nil

  def primary_image(html) do
    "<html><body>#{html}</body></html>"
    |> Readability.article()
    |> Floki.find("img")
    |> Floki.attribute("src")
    |> Enum.reject(fn str -> String.starts_with?(str, "https://medium.com/_/stat") end)
    |> List.first()
  end

  def has_primary_image(content), do: not (content |> primary_image() |> is_nil())

  def boolean_link(text, enabled, opts) when is_boolean(enabled) do
    opts =
      if enabled do
        opts
      else
        opts ++ [disabled: ""]
      end

    link(text, opts)
  end

  def pagination_link_opts(conn, page, pagination) do
    is_current = page == pagination.current_page
    opts = [to: Routes.blog_page_path(conn, :index, page), "aria-label": "Goto page #{page}"]

    if is_current do
      opts ++ [class: "pagination-link is-current", "aria-current": "page"]
    else
      opts ++ [class: "pagination-link"]
    end
  end
end

lib/alewordfire_web/views/shared_view.ex
defmodule AlewordfireWeb.SharedView do
  use AlewordfireWeb, :view
end

lib/alewordfire_web/templates/about/description.html.eex
<h4>Jade Alejandra Ornelas Figueroa</h4>
<p>
  <small class="is-tooltip-bottom tooltip" data-tooltip="Jorge Alejandro Figueroa Perez">
    Former name for legal purposes
  </small>
</p>
<p>
  Software Engineer with the passion to develop software. I am deeply interested in mobile development for Android, DevOps and backend development, especially in newer and promising technologies like Nodejs, Ruby/Rails, ElasticSearch, AWS,  etc…
</p>
<p>
  I have been programming since Secondary School, and have tried multiple languages and platforms. So far liking Ruby/Rails, Javascript/Node.js, C#/.NET and Kotlin/Android the most.
</p>

<p>
  I love to read everything about tech, and I try to hack every single gadget in my hands.
</p>

<p>
  Currently, I have a router with tomato-wrt working as my personal server, proud owner of a Hackintosh,  I also enjoy the music, and have played guitar for about 11 years, but mostly as a casual hobby and not as a professional guitarist.
</p>
<p>
  Always looking for LGBT+ friendly environment.
</p>
<p>
    Exchange Student in
    <span class="has-text-weight-bold is-size-5">Computer Software Education</span>
    at <a href="//cs.korea.edu" target="_blank">Korea University</a>
    <br />
    <small>February 2015 - June 2015, Seoul, South Korea</small>
  </p>
<p>
  Bachelors Degree in 
  <span class="has-text-weight-bold is-size-5">Software Engineering</span>
  at <a href="//telematicanet.ucol.mx/" target="_blank">Universidad de Colima</a>
  <br />
  <small>August 2012 - June 2016, Colima, México</small>
</p>

lib/alewordfire_web/templates/about/experience.html.eex
<%= render_many Alewordfire.Data.Experience.data, AlewordfireWeb.AboutView, "single_experience.html", as: :e %>  

lib/alewordfire_web/templates/about/index.html.eex
<div class="column is-three-fifths is-offset-one-fifth about" id="about"">
  <div class="columns">
    <%= render_section(
          "description.html",
          column_class: "column is-full has-card-top-margin",
          title: "Resume",
          icon: "align-justify"
        ) %> 
  </div>
  <div class="columns">
    <%= render_section(
      "skills.html",
      column_class: "column is-half",
      title: "Skills",
      icon: "pencil-alt"
    ) %>  
    <%= render_section(
      "experience.html",
      column_class: "column is-half",
      title: "Experience",
      icon: "laptop"
    ) %>  
  </div>
</div>

lib/alewordfire_web/templates/about/section.html.eex
<% column_class = assigns[:column_class] || "column is-full" %>
<div class="<%= column_class %>">
  <div class="card">
    <header class="card-header">
      <h1 class="card-header-title">
        <%= @title %>
      </h1>
      <a class="card-header-icon" aria-label="icon">
        <span class="icon">
          <i class="fas fa-<%= @icon %>" aria-hidden="true"></i>
        </span>
      </a>
    </header>
    <div class="card-content">
      <div class="content">
        <%= render AlewordfireWeb.AboutView, @template, assigns %>
      </div>
    </div>
  </div>
</div>
  

lib/alewordfire_web/templates/about/single_experience.html.eex
<p>
  <span class="has-text-weight-bold is-size-5"><%= @e["title"] %></span> / <%= @e["position"] %>
  <br />
  <small><%= @e["from"] %> - <%= @e["to"] %>, <%= @e["location"] %></small>
</p>
<p>
  <%= text_to_html(@e["description"]) %>
</p>
<ul>
  <%= Enum.map(@e["list"], fn t -> %>
  <li><%= t %></li>
  <% end) %>
</ul>
<br />

lib/alewordfire_web/templates/about/skills.html.eex
<ul>
    <li>Javascript (7 years)
    <ul>
    <li>ES6 (2 years)</li>
    <li>Node.js (6 years)</li>
    <li>Express.js (5 years)</li>
    <li>Koa (2 years)</li>
    <li>Angular.js (2 years)</li>
    <li>ReactJS (3 year)</li>
    <li>Unit Testing / Integration Testing / E2E Testing
    <ul>
    <li>Jest (2 years)</li>
    <li>Mocha (1 year)</li>
    <li><a href="http://Cypress.io">Cypress.io</a> (1 year)</li>
    </ul>
    </li>
    </ul>
    </li>
    <li>Java/Android (4 years)</li>
    <li>C# (3 years)</li>
    <li>Kotlin/Android (2 years)</li>
    <li>Elixir (1 year)
    <ul>
    <li>Phoenix (1 year)</li>
    <li>Unit Testing / Integration Testing / E2E Testing
    <ul>
    <li>ExUnit</li>
    </ul>
    </li>
    </ul>
    </li>
    <li>Ruby (3 years)
    <ul>
    <li>Rails (3 years)</li>
    <li>Unit Testing / Integration Testing / E2E Testing
    <ul>
    <li>Rspec</li>
    </ul>
    </li>
    </ul>
    </li>
    <li>Relational Databases
    <ul>
    <li>MySQL/MariaDB (3 years)</li>
    <li>PostgreSQL (4 year)</li>
    </ul>
    </li>
    <li>NoSQL Databases
    <ul>
    <li>DynamoDB (1 year)</li>
    <li>MongoDB (6 months)</li>
    </ul>
    </li>
    <li>Search Backends
    <ul>
    <li>ElasticSearch (6 months)</li>
    </ul>
    </li>
    <li>Containerization and Operating Systems
    <ul>
    <li>Docker (2 years)</li>
    <li>Linux (11 years)</li>
    <li>OSX (4 years)</li>
    <li>Windows (13 years)</li>
    </ul>
    </li>
    <li>Extras</li>
    <li>AWS [IAM, EC2, ECS, ELB, S3, Route53, IoT, DDB, Firehose, Lambda, Kinesis, ElasticBeanstalk] (2 years)</li>
    <li>Git (8 years)</li>
    <li>Github (6 years)</li>
    <li>API Security (OAuth, Basic, Token, JWT) (2 years)</li>
    <li>Scalable Web Services with AWS (2 years)</li>
    <li>TDD (3 years)</li>
    <li>Agile Development (3 years)</li>
    <li>Languages
    <ul>
    <li>Spanish (Native)</li>
    <li>English (Fluent - Cambridge: FCE B2, TOEFL IBT: 104)</li>
    <li>Korean (Beginner-Intermediate: TOPIK 1 A1)</li>
    <li>Japanese (Beginner)</li>
    </ul>
    </li>
    </ul>

lib/alewordfire_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= Metatags.print_tags(@conn) %>
    <% canonical_url = AlewordfireWeb.Router.Helpers.url(@conn) <> (@conn.assigns[:canonical_path] || @conn.request_path) %>
    <link rel="canonical" href="<%= canonical_url %>" />
    <link rel="preload" href="https://allfont.net/cache/css/tex-gyre-adventor.css" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript><link rel="stylesheet" href="https://allfont.net/cache/css/tex-gyre-adventor.css"></noscript>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <link rel="shortcut icon" href="<%= Routes.static_path(@conn, "/images/favicon.ico") %>"/>
    <link rel="apple-touch-icon" sizes="57x57" href="<%= Routes.static_path(@conn, "/images/apple-icon-57x57.png") %>"/>
    <link rel="apple-touch-icon" sizes="60x60" href="<%= Routes.static_path(@conn, "/images/apple-icon-60x60.png") %>"/>
    <link rel="apple-touch-icon" sizes="72x72" href="<%= Routes.static_path(@conn, "/images/apple-icon-72x72.png") %>"/>
    <link rel="apple-touch-icon" sizes="76x76" href="<%= Routes.static_path(@conn, "/images/apple-icon-76x76.png") %>"/>
    <link rel="apple-touch-icon" sizes="114x114" href="<%= Routes.static_path(@conn, "/images/apple-icon-114x114.png")
      %>"/>
    <link rel="apple-touch-icon" sizes="120x120" href="<%= Routes.static_path(@conn, "/images/apple-icon-120x120.png")
      %>"/>
    <link rel="apple-touch-icon" sizes="144x144" href="<%= Routes.static_path(@conn, "/images/apple-icon-144x144.png")
      %>"/>
    <link rel="apple-touch-icon" sizes="152x152" href="<%= Routes.static_path(@conn, "/images/apple-icon-152x152.png")
      %>"/>
    <link rel="apple-touch-icon" sizes="180x180" href="<%= Routes.static_path(@conn, "/images/apple-icon-180x180.png")
      %>"/>
    <link rel="icon" type="image/png" sizes="192x192" href="<%= Routes.static_path(@conn, "/images/android-icon-192x192.png")
      %>"/>
    <link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/images/favicon-32x32.png") %>"/>
    <link rel="icon" type="image/png" sizes="96x96" href="<%= Routes.static_path(@conn, "/images/favicon-96x96.png") %>"/>
    <link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/images/favicon-16x16.png") %>"/>
  </head>

  <body>
    <header>
      <%= render_shared "navbar.html", conn: @conn %>
      <%= render_shared "hero.html", conn: @conn %>
    </header>

    <main role="main" class="columns">
      <p class="alert alert-info" role="alert">
        <%= get_flash(@conn, :info) %>
      </p>
      <p class="alert alert-danger" role="alert">
        <%= get_flash(@conn, :error) %>
      </p>
      <%= render @view_module, @view_template, assigns %>
    </main>

    <footer class="footer">
      <div class="container">
        <div class="content has-text-centered">
          <p>
            <a class="icon" href="//github.com/jenil/bulmaswatch" target="_blank" onclick="ga('send', 'event', 'footer', 'click', 'github');">
              <i class="fab fa-github"></i>
            </a>
            &nbsp;
            <a class="icon" href="//t.me/yknx4" target="_blank" onclick="ga('send', 'event', 'footer', 'click', 'twitter');">
              <i class="fab fa-telegram"></i>
            </a>
          </p>
          <p>
            2018 - <strong>AleWorld</strong> by
            <a href="//github.com/yknx4" target="_blank">Ale Ornelas</a>
          </p>
        </div>
      </div>
    </footer>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>" ></script>
    <script defer src="https://use.fontawesome.com/releases/v5.6.3/js/all.js" integrity="sha384-EIHISlAOj4zgYieurP0SdoiBYfGJKkgWedPHH4jCzpCXLmzVsw1ouK59MuUtP4a1" crossorigin="anonymous"></script>
    <script type="text/javascript">
      /*! loadCSS. [c]2017 Filament Group, Inc. MIT License */
/* This file is meant as a standalone workflow for
- testing support for link[rel=preload]
- enabling async CSS loading in browsers that do not support rel=preload
- applying rel preload css once loaded, whether supported or not.
*/
(function( w ){
	"use strict";
	// rel=preload support test
	if( !w.loadCSS ){
		w.loadCSS = function(){};
	}
	// define on the loadCSS obj
	var rp = loadCSS.relpreload = {};
	// rel=preload feature support test
	// runs once and returns a function for compat purposes
	rp.support = (function(){
		var ret;
		try {
			ret = w.document.createElement( "link" ).relList.supports( "preload" );
		} catch (e) {
			ret = false;
		}
		return function(){
			return ret;
		};
	})();

	// if preload isn't supported, get an asynchronous load by using a non-matching media attribute
	// then change that media back to its intended value on load
	rp.bindMediaToggle = function( link ){
		// remember existing media attr for ultimate state, or default to 'all'
		var finalMedia = link.media || "all";

		function enableStylesheet(){
			// unbind listeners
			if( link.addEventListener ){
				link.removeEventListener( "load", enableStylesheet );
			} else if( link.attachEvent ){
				link.detachEvent( "onload", enableStylesheet );
			}
			link.setAttribute( "onload", null ); 
			link.media = finalMedia;
		}

		// bind load handlers to enable media
		if( link.addEventListener ){
			link.addEventListener( "load", enableStylesheet );
		} else if( link.attachEvent ){
			link.attachEvent( "onload", enableStylesheet );
		}

		// Set rel and non-applicable media type to start an async request
		// note: timeout allows this to happen async to let rendering continue in IE
		setTimeout(function(){
			link.rel = "stylesheet";
			link.media = "only x";
		});
		// also enable media after 3 seconds,
		// which will catch very old browsers (android 2.x, old firefox) that don't support onload on link
		setTimeout( enableStylesheet, 3000 );
	};

	// loop through link elements in DOM
	rp.poly = function(){
		// double check this to prevent external calls from running
		if( rp.support() ){
			return;
		}
		var links = w.document.getElementsByTagName( "link" );
		for( var i = 0; i < links.length; i++ ){
			var link = links[ i ];
			// qualify links to those with rel=preload and as=style attrs
			if( link.rel === "preload" && link.getAttribute( "as" ) === "style" && !link.getAttribute( "data-loadcss" ) ){
				// prevent rerunning on link
				link.setAttribute( "data-loadcss", true );
				// bind listeners to toggle media back
				rp.bindMediaToggle( link );
			}
		}
	};

	// if unsupported, run the polyfill
	if( !rp.support() ){
		// run once at least
		rp.poly();

		// rerun poly on an interval until onload
		var run = w.setInterval( rp.poly, 500 );
		if( w.addEventListener ){
			w.addEventListener( "load", function(){
				rp.poly();
				w.clearInterval( run );
			} );
		} else if( w.attachEvent ){
			w.attachEvent( "onload", function(){
				rp.poly();
				w.clearInterval( run );
			} );
		}
	}


	// commonjs
	if( typeof exports !== "undefined" ){
		exports.loadCSS = loadCSS;
	}
	else {
		w.loadCSS = loadCSS;
	}
}( typeof global !== "undefined" ? global : this ) );
    </script>
  </body>

</html>

lib/alewordfire_web/templates/page/index.html.eex
<div class="column is-three-fifths is-offset-one-fifth posts" id="posts">
  <% data = Alewordfire.Data.Feed.data %>
  <% posts = filter_posts(data.entries) %>
  <% paginator = create_paginator(posts) %>
  <% pagination = paginate(paginator, @conn.path_params) %>
  <%= render(
      AlewordfireWeb.PageView, 
      "posts.html", 
      posts: paginate_posts(posts, pagination)
      )%>
  <%= render(
      AlewordfireWeb.PageView, 
      "pagination.html",
      pagination: pagination,
      conn: @conn
      )%>
</div>

lib/alewordfire_web/templates/page/pagination.html.eex
<nav class="pagination is-right" role="navigation" aria-label="pagination">
  <%= boolean_link("Previous", @pagination.has_previous, to: Routes.blog_page_path(@conn, :index, @pagination.previous_page), class: "pagination-previous") %>
  <%= boolean_link("Next page", @pagination.has_next, to: Routes.blog_page_path(@conn, :index, @pagination.next_page), class: "pagination-next") %>
  <ul class="pagination-list">
    <li><a class="pagination-link" aria-label="Goto page 1" href="<%= Routes.blog_page_path(@conn, :index, 1) %>">1</a></li>
    <li><span class="pagination-ellipsis">&hellip;</span></li>
    <%= render_many Range.new(@pagination.current_page, min(@pagination.total_pages, @pagination.current_page + 2)), AlewordfireWeb.PageView, "pagination_link.html", as: :i, conn: @conn, pagination: @pagination  %>
    <li><span class="pagination-ellipsis">&hellip;</span></li>
    <li><a class="pagination-link" aria-label="Goto page <%= @pagination.total_pages %>" href="<%= Routes.blog_page_path(@conn, :index, @pagination.total_pages) %>">
        <%= @pagination.total_pages %></a></li>
  </ul>
</nav>

lib/alewordfire_web/templates/page/pagination_link.html.eex
<li>
  <%= link(@i, pagination_link_opts(@conn, @i, @pagination)) %>
</li>

lib/alewordfire_web/templates/page/post.html.eex
<% post_id = "post-#{post_ts(@page.updated)}" %>
<article class="card post" id="<%= post_id %>">
  <div class="card-content">
    <div class="media">
      <div class="media-left">
        <%= if has_primary_image(@page.content) do %>
        <figure class="image is-64x64 is-square">
          <img src="<%= primary_image(@page.content) %>" alt="Image">
        </figure>
        <% else %>
        <span class="is-64x64 is-square">
          <i class="fab fa-medium" aria-hidden="true"></i>
        </span>
        <% end %>
      </div>
      <div class="media-content">
        <a href="<%= @page.url %>" target="_blank">
          <p class="title is-4">
            <%= @page.title %>
          </p>
        </a>
        <p class="subtitle is-6">
          <%= post_date(@page.updated) %>
        </p>
      </div>
    </div>

    <div class="content post-content">
      <%= raw(@page.content) %>
    </div>
    <div class="fade"></div>
    <nav class="level">
      <div class="level-left">
        <div class="level-item"> </div>
      </div>
      <div class="level-right">
        <div class="level-item">
          <a href="#<%= post_id %>" class="card-header-icon show" aria-label="show more">
            Show more
            <span class="icon">
              <i class="fas fa-angle-down" aria-hidden="true"></i>
            </span>
          </a>
          <a href="#posts" class="hide" aria-label="hide content">
            Hide
            <span class="icon">
              <i class="fas fa-angle-up" aria-hidden="true"></i>
            </span>
          </a>
        </div>
      </div>
    </nav>
  </div>
</article>

lib/alewordfire_web/templates/page/posts.html.eex
<%= render_many @posts, AlewordfireWeb.PageView, "post.html" %>  
 

lib/alewordfire_web/templates/shared/hero.html.eex
<section class="hero is-primary">
  <div class="hero-body">
    <div class="container has-text-centered">
      <div class="columns">
        <div class="column is-offset-one-quarter is-half">
          <div class="columns is-vcentered">
            <div class="column">
              <h1 class="title font-title ">
                Ale&nbsp;<span class="has-text-red-main">Ornelas</span>
              </h1>
              <h2 class="subtitle">
                Devops Engineer, Social Rebel Transgirl, LifeHacker & Language Lover
              </h2>
            </div>
            <div class="column is-narrow">
              <a href="<%= Routes.about_path(@conn, :index) %>">
                <figure class="image is-128x128 is-pulled-right">
                  <img class="is-rounded" src="<%= Routes.static_path(@conn, "/images/ale.jpg") %>" alt="Ale Ornelas
                  profile picture">
                </figure>
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

lib/alewordfire_web/templates/shared/navbar.html.eex
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-start">
      <a class="navbar-item is-hidden-mobile" href="<%= Routes.page_path(@conn, :index) %>">
        <img src="<%= Routes.static_path(@conn, "/images/aleworld-logo.png") %>" alt="Ale World Logo" class="logo
        image" >
      </a>
      <a class="navbar-item" href="<%= Routes.page_path(@conn, :index) %>">
        <h1 class="font-title title is-5 has-text-white">ale<span class="has-text-red-main">world</span></h1>
      </a>
    </div>
    <span class="navbar-toggle">
      <span></span>
      <span></span>
      <span></span>
    </span>
    <div class="navbar-end navbar-menu">
      <a class="navbar-item" href="<%= Routes.about_path(@conn, :index) %>">
        About
      </a>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown is-boxed">
          <%= render_shared(
            "social_link.html", 
            title: "Telegram", 
            icon: "telegram",
            link: "//t.me/yknx4"
            )%>
          <%= render_shared(
            "social_link.html", 
            title: "Email", 
            icon: "envelope",
            link: "mailto:me@ale.world",
            type: "fas"
            )%>        
          <%= render_shared(
            "social_link.html", 
            title: "Github", 
            icon: "github",
            link: "//github.com/yknx4"
            )%>
          <%= render_shared(
            "social_link.html", 
            title: "LinkedIn", 
            icon: "linkedin",
            link: "//www.linkedin.com/yknx4"
            )%>  
          <%= render_shared(
            "social_link.html", 
            title: "Facebook", 
            icon: "facebook",
            link: "//www.facebook.com/yknx4"
            )%>
        </div>
      </div>
    </div>
  </div>
  </div>
</nav>

lib/alewordfire_web/templates/shared/social_link.html.eex
<a class="navbar-item" href="<%= @link %>" target="_blank">
  <span class="icon">
    <i class="<%= assigns[:type] || "fab" %> fa-<%= @icon %>" aria-hidden="true"></i>
  </span>
  <span><%= @title %></span>
</a>